name: Update OBD Data

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
             
      - name: Fetch OBD JSON
        run: |
          curl -X POST "https://www.obd-facile.fr/vehicle/tools/connectorv2-en.json" \
            -d "language=de" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -H "User-Agent: WOBD-App/1.0" \
            > data.json

      - name: Fetch Manufacturers JSON
        run: |
          curl -s "https://www.klavkarr.de/include/ajax/list_marques_connecteur.php" \
            -H "User-Agent: Mozilla/5.0" \
            > manufacturers.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Bitte ein Git!"
          git add data.json manufacturers.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Update OBD and Manufacturer data" && git push)
