# GitHub Action workflow definition
name: Update OBD Data

# Trigger workflow daily and manually
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

# Define jobs
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4
      
      # Fetch JSON data via curl
      - name: Fetch JSON
        run: |
          curl -X POST "https://www.obd-facile.fr/vehicle/tools/connectorv2-en.json" \
            -d "language=de" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -H "User-Agent: WOBD-App/1.0" \
            > data.json

      # Commit and push changes if any
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Bitte ein Git!"
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Update OBD data" && git push)